- name: Checkout repo
  uses: actions/checkout@v2
  with:
    fetch-depth: 3
- name: Run yor action
  uses: bridgecrewio/yor-action@main
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
